---
- name: Re-run setup to load local facts
  setup: filter=ansible_local

- name: Activate patched ABE
  shell: /usr/sbin/luactivate {{ ansible_local.pca.abe.pending }}
  register: activated
  changed_when: "activated.stdout != 'WARNING: Boot environment <{{ ansible_local.pca.abe.pending }}> is already activated.'"
  notify: reboot sequence
