---
- name: Get Patch Bundle Size
  shell: for i in `cat {{ pca_basedir }}/{{ inventory_hostname }}/patchlist.out` ; do du -sk {{ pca_basedir }}/patches/$i ; done | awk '{ sum +=$1 } END {print sum}'
  delegate_to: localhost
  register: pca_bundlesize
  changed_when: false

- name: Check there is enough free space in defined tempdir
  shell: /usr/bin/df -b {{ pca_tempdir }} | /usr/bin/tail -1 | /usr/bin/awk '{print $2}'
  register: tempspace
  failed_when: "tempspace.stdout|int <= pca_bundlesize.stdout|int*2"
  changed_when: false

- name: Get zones root filesystems to check for space
  shell: /usr/sbin/zoneadm list -cvi | /usr/bin/awk '$5=="native" {print $4}'
  register: zoneroot
  changed_when: false

- name: Check there is enough free space in each zone root FS
  shell: /usr/bin/df -b {{ item }} | /usr/bin/tail -1 | /usr/bin/awk '{print $2}'
  register: zonerootspace
  failed_when: "zonerootspace.stdout|int <= pca_bundlesize.stdout|int*4"
  with_items: "{{ zoneroot.stdout_lines }}"
  changed_when: false
