---
- name: Get Patch Bundle Size
  local_action: shell bundlesize=0 ; for i in `cat {{ pca_basedir }}/{{ inventory_hostname }}/patchlist.out` ; do filesize=`du -sk {{ pca_basedir }}/patches/$i | awk '{print $1}'` ; bundlesize=$(($bundlesize+$filesize)) ; done ; echo $bundlesize
  register: pca_bundlesize
  changed_when: false

- name: Check there is enough free space in defined tempdir
  shell: df -b {{ pca_tempdir }} | tail -1 | awk '{print $2}'
  register: tempspace
  failed_when: "tempspace.stdout|int <= pca_bundlesize.stdout|int*3"
  changed_when: false

- name: Get zones root filesystems to check for space
  shell: "awk -F: '!/^#/{ print $3 }' /etc/zones/index"
  register: zoneroot
  changed_when: false

- name: Check there is enough free space in each zone root FS
  shell: df -b {{ item }} | tail -1 | awk '{print $2}'
  register: zonerootspace
  failed_when: "zonerootspace.stdout|int <= pca_bundlesize.stdout|int*3"
  with_items: "{{ zoneroot.stdout_lines }}"
  changed_when: false
