---
- name: Upload patches to server
  synchronize: src={{ pca_basedir }}/patches
               dest={{ pca_tempdir }}/pca_patches
               compress=no
               rsync_opts="--files-from={{ pca_basedir }}/{{ inventory_hostname }}/patchlist.out"
