---
- name: Gather facts
  setup:
  always_run: true
  tags: health,setup,cleanup,check,stage,install,activate

- include: health.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: health

- include: setup.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: setup

- include: cleanup.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: cleanup

- include: stage.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: stage

- include: check.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: check

- include: deploy.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: deploy

- include: install.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: install

- include: activate.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  tags: activate
