---

# Fail there is no ZFS root

- name: Check server has ZFS root
  shell: /usr/sbin/df -n /
  register: dfroot
  failed_when: "'zfs' not in dfroot.stdout"
  changed_when: false

# Fail if Live Upgrade is not already configured and working

- name: Check server has Live Upgrade properly initialized
  shell: /usr/sbin/lucurr
  changed_when: false

# Check for an ABE already patched with this role
# fail if there is one already

- name: Check if there is an ABE pending activation
  command: /usr/bin/grep pending /etc/ansible/facts.d/pca.fact
  changed_when: false
  failed_when: pca_abe_pending.rc == 0
  register: pca_abe_pending
  tags: health,setup,cleanup,analyze,check,stage,install,activate
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined

# All tags below call for each subset of the role tasks

- include: setup.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  - pca_abe_pending.rc != '0'
  tags: setup

- include: analyze.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  - pca_abe_pending.rc != '0'
  tags: analyze

- include: stage.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  - pca_abe_pending.rc != '0'
  tags: stage

- include: cleanup.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  - pca_abe_pending.rc != '0'
  tags: cleanup

- include: health.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  - pca_abe_pending.rc != '0'
  tags: health

- include: check.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  - pca_abe_pending.rc != '0'
  tags: check

- include: deploy.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  - pca_abe_pending.rc != '0'
  tags: deploy

- include: install.yml
  when:
  - ansible_os_family == 'Solaris'
  - ansible_distribution_version == '10'
  - ansible_container is not defined
  - pca_abe_pending.rc != '0'
  tags: install
