---
# tasks file for solaris-pca-patching
- name: Cleanup working environment
  file: path={{ pca_tempdir }}/pca_patches
        state=absent

- name: Setup working directory
  local_action: shell mkdir -p {{ pca_basedir }}/{{ inventory_hostname }}

- name: Get PCA script
  get_url: 
    url: http://www.par.univie.ac.at/solaris/pca/download/pca-20150327-01
    dest: "{{ pca_basedir }}/pca"
    owner: root
    group: root
    mode: 0755
    checksum: md5:2745e21d035aa068ae23a530a9378dff
  delegate_to: localhost
  run_once: true
  when: pca_downloadfirst

- name: Update PCA
  local_action: shell {{ pca_basedir }}/pca --update now
  register: updatepca
  changed_when: updatepca.stdout != 'No new version available'
  run_once: true

- name: Set cronjob for downloading patchdiag.xref on desired schedule
  cron: name='Download patchdiag file from oracle'
        cron_file=/etc/crontab
        user=root
        minute={{ pca_patchdiag_minute_schedule }}
        hour={{ pca_patchdiag_hour_schedule }}
        day={{ pca_patchdiag_dom_schedule }}
        month={{ pca_patchdiag_monthly_schedule }}
        dow={{ pca_patchdiag_dow_schedule }}
        job='wget --no-check-certificate https://getupdates.oracle.com/reports/patchdiag.xref -O {{ pca_basedir }}/patchdiag.xref.`date +%Y%m%d`'
  delegate_to: localhost
  run_once: true

- name: Get which is the latest available patchdiag file
  local_action: shell ls -t `find /var/pca -name patchdiag.xref.20[1-2][0-9][0-1][0-9][0-3][0-9]` 2>/dev/null | head -n1
  register: latest_patchdiag
  changed_when: false
  run_once: true

- name: Download latest patchdiag.xref if there is none present
  local_action: shell wget --no-check-certificate https://getupdates.oracle.com/reports/patchdiag.xref -O {{ pca_basedir }}/patchdiag.xref.`date +%Y%m%d`
  run_once: true
  when: latest_patchdiag.stdout == ""

- name: Set patchdiag target file variable
  local_action: shell ls -t `find /var/pca -name patchdiag.xref.20[1-2][0-9][0-1][0-9][0-3][0-9]` 2>/dev/null | head -n1
  register: active_patchdiag_file
  changed_when: false
  run_once: true

- name: Link latest patchdiag for use by PCA
  file: src={{ active_patchdiag_file.stdout }}
        state=link
        path={{ pca_basedir }}/patchdiag.xref
  delegate_to: localhost
  run_once: true

- name: Collect information from target Solaris system for PCA
  shell: showrev -p > {{ pca_tempdir }}/showrev.out ; uname -a > {{ pca_tempdir }}/uname.out ; pkginfo -x > {{ pca_tempdir }}/pkginfo.out

- name: Pull files for PCA analysis
  fetch: dest={{ pca_basedir }}/{{ inventory_hostname }}
         src={{ pca_tempdir }}/{{ item }}
         fail_on_missing=yes
         flat=yes
  with_items:
  - showrev.out
  - uname.out
  - pkginfo.out

- name: Generate patchlist
  local_action: shell {{ pca_basedir }}/pca -l {{ solaris_pca_operand }} -y -X {{ pca_basedir }} -f {{ pca_basedir }}/{{ inventory_hostname }} | egrep '^1' | awk '{ print "{{ pca_basedir }}/patches/" $1 "-" $4 ".zip" }' > {{ pca_basedir }}/{{ inventory_hostname }}/patchlist.out

- name: Append prereq patchlist
  local_action: shell {{ pca_basedir }}/pca -l {{ pca_prereq }} -y -X {{ pca_basedir }} -f {{ pca_basedir }}/{{ inventory_hostname }} | egrep '^1' | awk '{ print "{{ pca_basedir }}/patches/" $1 "-" $4 ".zip" }' >> {{ pca_basedir }}/{{ inventory_hostname }}/patchlist.out

- name: Download required patches from Oracle
  local_action: shell {{ pca_basedir }}/pca -d {{ solaris_pca_operand }} -y -X {{ pca_basedir }} -f {{ pca_basedir }}/{{ inventory_hostname }} -P {{ pca_basedir }}/patches --user={{ mos_user }} --passwd={{ mos_password }}

- name: Download prereq patches from Oracle
  local_action: shell {{ pca_basedir }}/pca -d {{ pca_prereq }} -y -X {{ pca_basedir }} -f {{ pca_basedir }}/{{ inventory_hostname }} -P {{ pca_basedir }}/patches --user={{ mos_user }} --passwd={{ mos_password }}

- name: Get Patch Bundle Size
  local_action: shell bundlesize=0 ; for i in `cat {{ pca_basedir }}/{{ inventory_hostname }}/patchlist.out` ; do filesize=`du -sk $i | awk '{print $1}'` ; bundlesize=$(($bundlesize+$filesize)) ; done ; echo $bundlesize
  register: pca_bundlesize
  changed_when: false

- name: Check there is enough free space in defined tempdir
  shell: df -b {{ pca_tempdir }} | tail -1 | awk '{print $2}'
  register: tempspace
  failed_when: "tempspace.stdout|int <= pca_bundlesize.stdout|int*3"
  changed_when: false

- name: Get zones root filesystems to check for space
  shell: "awk -F: '!/^#/{ print $3 }' /etc/zones/index"
  register: zoneroot
  changed_when: false

- name: Check there is enough free space in each zone root FS
  shell: df -b {{ item }} | tail -1 | awk '{print $2}'
  register: zonerootspace
  failed_when: "zonerootspace.stdout|int <= pca_bundlesize.stdout|int*3"
  with_items: "{{ zoneroot.stdout_lines }}"
  changed_when: false

- name: Upload patches to server
  synchronize: src={{ pca_basedir }}/patches
               dest={{ pca_tempdir }}/pca_patches
               compress=no
               rsync_opts="--files-from={{ pca_basedir }}/{{ inventory_hostname }}/patchlist.out"

- name: Upload PCA script
  copy: src={{ pca_basedir }}/pca
        dest={{ pca_tempdir }}/pca
        owner=root
        group=root
        mode=0755

- name: Upload patchdiag.xref
  copy: src={{ pca_basedir }}/patchdiag.xref
        dest={{ pca_tempdir }}/pca_patches/patchdiag.xref
        owner=root
        group=root
        mode=0644

- name: get current date for reference as ABE name
  command: date +%Y%m%d
  register: pca_abe
  changed_when: false
  always_run: true

- name: Install prerequisite patches in live BE
  shell: "{{ pca_tempdir }}/pca -i {{ pca_prereq }} -y -X {{ pca_tempdir }}/pca_patches -P {{ pca_tempdir }}/pca_patches"

- name: Create ABE
  shell: /usr/sbin/lucreate -n {{ pca_abe.stdout }}

- name: Mount ABE
  shell: /usr/sbin/lumount {{ pca_abe.stdout }}

- name: Fix for Sun CR 6804076
  lineinfile: dest=/.alt.{{ pca_abe.stdout }}/etc/zones/index
              regexp='^global{{":"}}configured.*'
              backrefs=yes
              line='global{{":"}}installed{{":"}}/'

- name: Dry Run patch installation to ABE
  shell: "{{ pca_tempdir }}/pca -I {{ solaris_pca_operand }} -y -X {{ pca_tempdir }}/pca_patches -P {{ pca_tempdir }}/pca_patches -R /.alt.{{ pca_abe.stdout }}"

- name: Install patches to ABE
  shell: "{{ pca_tempdir }}/pca -i {{ solaris_pca_operand }} -y -X {{ pca_tempdir }}/pca_patches -P {{ pca_tempdir }}/pca_patches -R /.alt.{{ pca_abe.stdout }}"

- name: Update ABE Ramdisk
  shell: /.alt.{{ pca_abe.stdout }}/boot/solaris/bin/create_ramdisk -R /.alt.{{ pca_abe.stdout }}

- name: Cleanup ABE pushed patch repo
  file: path=/.alt.{{ pca_abe.stdout }}{{ pca_tempdir }}/pca_patches
        state=absent

- name: Cleanup pushed patch repo
  file: path={{ pca_tempdir }}/pca_patches
        state=absent

- name: Umount ABE
  shell: /usr/sbin/luumount {{ pca_abe.stdout }}
