---
- name: Cleanup working environment
  file: path={{ pca_tempdir }}/pca_patches
        state=absent

- name: Setup working directory
  file: path={{ pca_basedir }}/{{ inventory_hostname }}
        state=directory
  delegate_to: localhost

- name: Get PCA script
  get_url: 
    url: http://www.par.univie.ac.at/solaris/pca/download/pca-20150327-01
    dest: "{{ pca_basedir }}/pca"
    owner: root
    group: root
    mode: 0755
    checksum: md5:2745e21d035aa068ae23a530a9378dff
  delegate_to: localhost
  run_once: true
  when: pca_downloadfirst

- name: Update PCA
  local_action: shell {{ pca_basedir }}/pca --update now
  register: updatepca
  changed_when: updatepca.stdout != 'No new version available'
  run_once: true

- name: Set cronjob for downloading patchdiag.xref on desired schedule
  cron: name='Download patchdiag file from oracle'
        cron_file=/etc/crontab
        user=root
        minute={{ pca_patchdiag_minute_schedule }}
        hour={{ pca_patchdiag_hour_schedule }}
        day={{ pca_patchdiag_dom_schedule }}
        month={{ pca_patchdiag_monthly_schedule }}
        dow={{ pca_patchdiag_dow_schedule }}
        job='wget --no-check-certificate https://getupdates.oracle.com/reports/patchdiag.xref -O {{ pca_basedir }}/patchdiag.xref.`date +%Y%m%d`'
  delegate_to: localhost
  run_once: true

- name: Get which is the latest available patchdiag file
  local_action: shell find {{pca_basedir }} -name patchdiag.xref.20[1-2][0-9][0-1][0-9][0-3][0-9] -exec ls -1t '{}' \;| head -n1 | wc -l
  register: latest_patchdiag
  changed_when: false
  run_once: true

- name: Download latest patchdiag.xref if there is none present
  local_action: shell wget --no-check-certificate https://getupdates.oracle.com/reports/patchdiag.xref -O {{ pca_basedir }}/patchdiag.xref.`date +%Y%m%d`
  run_once: true
  when: latest_patchdiag.stdout == '0'

- name: Set patchdiag target file variable
  local_action: shell ls -t `find /var/pca -name patchdiag.xref.20[1-2][0-9][0-1][0-9][0-3][0-9]` 2>/dev/null | head -n1
  register: active_patchdiag_file
  changed_when: false
  run_once: true

- name: Link latest patchdiag for use by PCA
  file: src={{ active_patchdiag_file.stdout }}
        state=link
        path={{ pca_basedir }}/patchdiag.xref
  delegate_to: localhost
  run_once: true

- name: Collect information from target Solaris system for PCA
  shell: showrev -p > {{ pca_tempdir }}/showrev.out ; uname -a > {{ pca_tempdir }}/uname.out ; pkginfo -x > {{ pca_tempdir }}/pkginfo.out

- name: Pull files for PCA analysis
  fetch: dest={{ pca_basedir }}/{{ inventory_hostname }}/{{ item }}
         src={{ pca_tempdir }}/{{ item }}
         fail_on_missing=yes
         flat=yes
  with_items:
  - showrev.out
  - uname.out
  - pkginfo.out

- name: Generate patchlist
  local_action: shell {{ pca_basedir }}/pca -l {{ solaris_pca_operand }} -y -X {{ pca_basedir }} -f {{ pca_basedir }}/{{ inventory_hostname }} | egrep '^1' | awk '{ print $1 "-" $4 ".zip" }' > {{ pca_basedir }}/{{ inventory_hostname }}/patchlist.out

- name: Place prereq file in global workdir
  copy: src={{ pca_prereq }}
        dest={{ pca_basedir }}/{{ pca_prereq }}
  delegate_to: localhost
  run_once: true

- name: Append prereq patchlist
  local_action: shell {{ pca_basedir }}/pca -l {{ pca_basedir }}/{{ pca_prereq }} -y -X {{ pca_basedir }} -f {{ pca_basedir }}/{{ inventory_hostname }} | egrep '^1' | awk '{ print $1 "-" $4 ".zip" }' >> {{ pca_basedir }}/{{ inventory_hostname }}/patchlist.out

- name: Setup pca patch dir repository
  file: path={{ pca_basedir }}/patches
        state=directory
  delegate_to: localhost
  run_once: true
