---
- name: check for space in temp filesystem to copy upgrade image
  shell: /usr/bin/df -b {{ pca_tempdir }} | /usr/bin/tail -1 | /usr/bin/awk '{print $2}'
  register: tempspace
  failed_when: "tempspace.stdout|int <= 3145728"
  changed_when: false

- name: Synchronize Solaris10u11 install image to target host
  synchronize: compress=no
               archive=yes
               src={{ pca_basedir }}/Solaris_10_0113/
               dest={{ pca_tempdir }}/Solaris_10_0113

- name: Remove Live Upgrade packages
  svr4pkg: name={{ item }}
           state=absent
  with_items:
  - SUNWlucfg
  - SUNWluu
  - SUNWlur

- name: Install Solaris10u11 Live Upgrade packages
  svr4pkg: name={{ item }}
           state=present
           src={{ pca_tempdir}}/Solaris_10_0113/Solaris_10/Product
  with_items:
  - SUNWlucfg
  - SUNWluu
  - SUNWlur

- name: Reapply Live Upgrade packages patch
  shell: "{{ pca_tempdir }}/pca -i 121430 -y -X {{ pca_tempdir }}/pca_patches -P {{ pca_tempdir }}/pca_patches"

- name: Set autoreg value
  copy: content="autoreg=disable"
        dest=/var/tmp/no-autoreg
        owner=root
        group=root
        mode=0644

- name: Upgrade to Solaris10u11
  shell: "( ( nohup /usr/sbin/luupgrade -u -n {{ pca_abe.stdout }} -s {{ pca_tempdir }}/Solaris_10_0113 -k /var/tmp/no-autoreg > {{ pca_tempdir }}/pca_patches/sol10u11_upgrade.log 2>&1& ) & )"
  args:
    executable: /usr/bin/bash
    chdir: "{{ pca_tempdir }}/pca_patches"
    creates: sol10u11_upgrade.log

- name: Wait for patch installation to complete
  wait_for: path={{ pca_tempdir }}/pca_patches/sol10u11_upgrade.log
            search_regex='^Failsafe install is complete.*$'
            state=present
            connect_timeout=60

- name: Get Upgrade log
  fetch: src={{ pca_tempdir }}/pca_patches/sol10u11_upgrade.log
         dest={{ pca_basedir }}}/{{ inventory_hostname }}/{{ inventory_hostname }}_sol10u11_upgrade.log
         flat=yes
         fail_on_missing=yes

- name: Email upgrade report
  shell: ( echo 'To{{":"}} {{ pca_destination_address }}'; echo 'From{{":"}} {{ pca_source_address }}'; echo 'Content-Type{{":"}} text/html'; echo 'MIME-Version{{":"}} 1.0'; echo 'Subject{{":"}} Solaris Patch Installation report - {{ inventory_hostname }}'; echo; cat {{ pca_basedir }}/{{ inventory_hostname }}/{{ inventory_hostname }}_sol10u11_upgrade.log ) | /usr/sbin/sendmail -t
  args:
    executable: /bin/bash
  delegate_to: localhost
  when:
  - pca_send_email

- name: Cleanup Solaris10u11 install image
  file: path=/Solaris_10_0113
        state=absent

- include: analyze.yml

- name: Install prerequisite patches in ABE after 10u11 upgrade
  shell: "{{ pca_tempdir }}/pca -i {{ pca_tempdir}}/pca_patches/{{ pca_prereq }} -y -X {{ pca_tempdir }}/pca_patches -P {{ pca_tempdir }}/pca_patches -R {{ pca_abe_mountpoint.stdout }}"

- include: stage.yml

- include: deploy.yml
